-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 12:53:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BierBuddyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ActivityPreferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ActivityPreferences` (
  `ActivityPreferencesID` BIGINT(128) NOT NULL,
  `Activities_ActivityID1` BIGINT(128) NOT NULL,
  `Activities_ActivityID2` BIGINT(128) NULL,
  `Activities_ActivityID3` BIGINT(128) NULL,
  `Activities_ActivityID4` BIGINT(128) NULL,
  PRIMARY KEY (`ActivityPreferencesID`),
  CONSTRAINT `fk_ActivityPreferences_Activities1`
    FOREIGN KEY (`Activities_ActivityID1`)
    REFERENCES `PossibleActivities` (`ActivityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActivityPreferences_Activities2`
    FOREIGN KEY (`Activities_ActivityID2`)
    REFERENCES `PossibleActivities` (`ActivityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActivityPreferences_Activities3`
    FOREIGN KEY (`Activities_ActivityID3`)
    REFERENCES `PossibleActivities` (`ActivityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActivityPreferences_Activities4`
    FOREIGN KEY (`Activities_ActivityID4`)
    REFERENCES `PossibleActivities` (`ActivityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dislikes` (
  `DislikerID` BIGINT(128) NOT NULL,
  `DislikedID` BIGINT(128) NOT NULL,
  PRIMARY KEY (`DislikerID`, `DislikedID`),
  CONSTRAINT `fk_Dislikes_Visitor1`
    FOREIGN KEY (`DislikerID`)
    REFERENCES `Visitor` (`VisitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dislikes_Visitor2`
    FOREIGN KEY (`DislikedID`)
    REFERENCES `Visitor` (`VisitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DrinkPreferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DrinkPreferences` (
  `DrinkPreferencesID` BIGINT(128) NOT NULL,
  `Drinks_DrinkID1` BIGINT(128) NOT NULL,
  `Drinks_DrinkID2` BIGINT(128) NULL,
  `Drinks_DrinkID3` BIGINT(128) NULL,
  `Drinks_DrinkID4` BIGINT(128) NULL,
  PRIMARY KEY (`DrinkPreferencesID`),
  CONSTRAINT `fk_DrinkPreferences_Drinks1`
    FOREIGN KEY (`Drinks_DrinkID1`)
    REFERENCES `PossibleDrinks` (`DrinkID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DrinkPreferences_Drinks2`
    FOREIGN KEY (`Drinks_DrinkID2`)
    REFERENCES `PossibleDrinks` (`DrinkID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DrinkPreferences_Drinks3`
    FOREIGN KEY (`Drinks_DrinkID3`)
    REFERENCES `PossibleDrinks` (`DrinkID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DrinkPreferences_Drinks4`
    FOREIGN KEY (`Drinks_DrinkID4`)
    REFERENCES `PossibleDrinks` (`DrinkID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Interests` (
  `InterestsID` BIGINT(128) NOT NULL,
  `PossibleInterests_InterestID1` BIGINT(128) NOT NULL,
  `PossibleInterests_InterestID2` BIGINT(128) NULL,
  `PossibleInterests_InterestID3` BIGINT(128) NULL,
  `PossibleInterests_InterestID4` BIGINT(128) NULL,
  PRIMARY KEY (`InterestsID`),
  CONSTRAINT `fk_Interests_PossibleInterests1`
    FOREIGN KEY (`PossibleInterests_InterestID1`)
    REFERENCES `PossibleInterests` (`InterestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interests_PossibleInterests2`
    FOREIGN KEY (`PossibleInterests_InterestID2`)
    REFERENCES `PossibleInterests` (`InterestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interests_PossibleInterests3`
    FOREIGN KEY (`PossibleInterests_InterestID3`)
    REFERENCES `PossibleInterests` (`InterestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interests_PossibleInterests4`
    FOREIGN KEY (`PossibleInterests_InterestID4`)
    REFERENCES `PossibleInterests` (`InterestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Likes` (
  `LikerID` BIGINT(128) NOT NULL,
  `LikedID` BIGINT(128) NOT NULL,
  PRIMARY KEY (`LikerID`, `LikedID`),
  CONSTRAINT `fk_Likes_Visitor1`
    FOREIGN KEY (`LikerID`)
    REFERENCES `Visitor` (`VisitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likes_Visitor2`
    FOREIGN KEY (`LikedID`)
    REFERENCES `Visitor` (`VisitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matches` (
  `Visitor_VisitorID1` BIGINT(128) NOT NULL,
  `Visitor_VisitorID2` BIGINT(128) NOT NULL,
  PRIMARY KEY (`Visitor_VisitorID1`, `Visitor_VisitorID2`),
  CONSTRAINT `fk_Matches_Visitor1`
    FOREIGN KEY (`Visitor_VisitorID1`)
    REFERENCES `Visitor` (`VisitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matches_Visitor2`
    FOREIGN KEY (`Visitor_VisitorID2`)
    REFERENCES `Visitor` (`VisitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Photo` (
  `PhotoID` BIGINT(128) NOT NULL,
  `Photo1URL` VARCHAR(200) NOT NULL,
  `Photo2URL` VARCHAR(200) NULL,
  `Photo3URL` VARCHAR(200) NULL,
  `Photo4URL` VARCHAR(200) NULL,
  PRIMARY KEY (`PhotoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PossibleActivities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PossibleActivities` (
  `ActivityID` BIGINT(128) NOT NULL,
  `Activity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ActivityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PossibleDrinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PossibleDrinks` (
  `DrinkID` BIGINT(128) NOT NULL,
  `Drink` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DrinkID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PossibleInterests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PossibleInterests` (
  `InterestID` BIGINT(128) NOT NULL,
  `Interest` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`InterestID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Visitor` (
  `VisitorID` BIGINT(128) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Bio` VARCHAR(400) NOT NULL,
  `Photo_PhotoID` BIGINT(128) NOT NULL,
  `DrinkPreferences_DrinkPreferencesID` BIGINT(128) NOT NULL,
  `Interests_InterestsID` BIGINT(128) NOT NULL,
  `ActivityPreferences_ActivityPreferencesID` BIGINT(128) NOT NULL,
  PRIMARY KEY (`VisitorID`),
  CONSTRAINT `fk_Visitor_Photo`
    FOREIGN KEY (`Photo_PhotoID`)
    REFERENCES `Photo` (`PhotoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitor_DrinkPreferences1`
    FOREIGN KEY (`DrinkPreferences_DrinkPreferencesID`)
    REFERENCES `DrinkPreferences` (`DrinkPreferencesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitor_Interests1`
    FOREIGN KEY (`Interests_InterestsID`)
    REFERENCES `Interests` (`InterestsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitor_ActivityPreferences1`
    FOREIGN KEY (`ActivityPreferences_ActivityPreferencesID`)
    REFERENCES `ActivityPreferences` (`ActivityPreferencesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
