name: Check for changed file

on:
  pull_request:
    branches: [main]

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39 1
      - name: Check if specific file is changed
        if: contains(steps.changed-files.outputs.all_changed_files, 'BierBuddy.DataAccess/*')
        run: echo "Er is een bestand veranderd in de DataAccess, run lokaal de DataAccessTests!"
